<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4426" started-at="2016-02-12T18:13:51Z" finished-at="2016-02-12T18:13:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4426" started-at="2016-02-12T18:13:51Z" finished-at="2016-02-12T18:13:55Z">
      <class name="com.example.selenium.spree.ShoppingSpreeTests">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.example.selenium.spree.ShoppingSpreeTests@5abca1e0]" test-instance-name="" name="beforeMethod" is-config="true" duration-ms="3583" started-at="2016-02-12T13:13:51Z" finished-at="2016-02-12T13:13:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="testProductPageTitle()[pri:0, instance:com.example.selenium.spree.ShoppingSpreeTests@5abca1e0]" test-instance-name="" name="testProductPageTitle" duration-ms="826" started-at="2016-02-12T13:13:54Z" finished-at="2016-02-12T13:13:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.example.selenium.spree.ShoppingSpreeTests.testProductPageTitle(ShoppingSpreeTests.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testProductPageTitle -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.example.selenium.spree.ShoppingSpreeTests@5abca1e0]" test-instance-name="" name="afterMethod" is-config="true" duration-ms="0" started-at="2016-02-12T13:13:55Z" finished-at="2016-02-12T13:13:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="testCartPageTitle()[pri:0, instance:com.example.selenium.spree.ShoppingSpreeTests@5abca1e0]" test-instance-name="" name="testCartPageTitle" duration-ms="0" started-at="2016-02-12T13:13:55Z" depends-on-methods="com.example.selenium.spree.ShoppingSpreeTests.testProductPageTitle" finished-at="2016-02-12T13:13:55Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ShoppingSpreeTests.testCartPageTitle()[pri:0, instance:com.example.selenium.spree.ShoppingSpreeTests@5abca1e0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ShoppingSpreeTests.testCartPageTitle()[pri:0, instance:com.example.selenium.spree.ShoppingSpreeTests@5abca1e0] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCartPageTitle -->
      </class> <!-- com.example.selenium.spree.ShoppingSpreeTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
